// docker-dev-env-setups-main/svelte-pocketbase/app/src/App.svelte
<script lang="ts">
  import Router from "svelte-spa-router";
  import Home from "./views/Home.svelte";
  import Navbar from "./components/Navbar.svelte";
  import Login from "./views/Login.svelte";
  import Register from "./views/Register.svelte";

  const routes = {
    "/": Home,
    "/login": Login,
    "/register": Register,
  };
</script>

<main>
  <Navbar />
  <Router {routes} />
</main>

<style>
</style>

// docker-dev-env-setups-main/dotnet6-reactjs-mssql/front-end/src/App.jsx
import { BrowserRouter, Routes, Route } from 'react-router-dom'
import './App.css'
import { NavigationBar } from './components/navbar/navbar'
import { Categories } from './views/Categories/categories'
import { Home } from './views/home/home'
import { Items } from './views/Items/items'

const App = () => {

  return (
    <BrowserRouter>

      <NavigationBar />

      <div className="App">
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/Categories" element={<Categories />} />
          <Route path="/Items" element={<Items />} />
        </Routes>
      </div>
    </BrowserRouter>
  )
}


export default App
